### ISSUE TITLE
Causes resource packs to fail in 1.17.1

### ISSUE THREAD

**Issue by UntalentedAmateur** [AMereBagatelle/fabricskyboxes#25] opened 2021-10-03 02:32 UTC
I was going through and updating my 1.17.1 Fabric supported world and found that any OF converted skybox packs (via MCPPPP command line or GUI) would cause fabricskyboxes to panic and make Minecraft unload ALL resource packs.

I then tried with the latest Awesome Skies pack from Curseforge, and found the same panic and unload of resource packs.  I also tried with the MiASkyboxFabric skybox, and same issue.

Unloading ALL fabric converted and dedicated fabric skyboxes from the active resourcepacks, and then leaving OF skyboxes active seemed to be somewhat okay, though the MCPPPP fabric mod doing on-the-fly translation didn't actually result in any changes to the skybox.  I can swap between an OF and fabric install to check the function of the skybox, so can verify that the resourcepack is actually functioning.

Loaded fabric (0.7.4 client) mods are:
fabricskyboxes 0.5.2
iris-and-sodium 1.1.2+build.9
lithium 0.7.4
mcpppp 0.5.2
plasmovoice fabric 1.0.13
starlight 1.0.0 (73f6d37)

I've gone through and unloaded all mods and put them back to find where the resource unload was happening, and it's triggered only by fabricskyboxes, and only when there's a skybox resource pack / resourcepack with fabric configuration in the active resourcepack list.

**Comment by supsm** [comment] 2021-10-03 03:19
We will need more information (logs and resource pack). You can reply in supsm/MCPPPP#11, here, or both. @AMereBagatelle The unloading of packs seems to be fabricskyboxes' issue, if awesome skies causes this as well.  
As for the mod version, I will need to know the operating system and will need logs as well.

**Comment by UntalentedAmateur** [comment] 2021-10-03 07:52
I'll work on getting those details for you later today.  Thanks also for duplicating this across on MCPPPP, but I don't really think it's an issue for MCPPPP, unless MiASkybox and Awesome Skies used it when generating their fabric skyboxes.  The more eyes on it, the better, though, I guess.

**Comment by UntalentedAmateur** [comment] 2021-10-03 12:07
Ok, log attached, with PII redacted.

The log jumps around a bit as I'm moving mods in and out trying to track down what's happened, but I can see the force reload taking place, and it claiming that the reason is due to fabricskyboxes.  I can see it happening for multiple different skybox variants.  System config is at the start of the log, but I'm running OS X Big Sur 11.6, fully updated, with 64GB RAM.  Minecraft is using the default JVM invocations for a fabric install (-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M).

[2021-10-02-6.log](https://github.com/AMereBagatelle/fabricskyboxes/files/7273276/2021-10-02-6.log)

**Comment by AMereBagatelle** [comment] 2021-10-03 15:29
There's a ton of noise in the log due to other mods and resource packs, could you try removing all extra mods and/or resource packs and reproducing?  I'll be attempting to reproduce it myself in a few minutes.

**Comment by UntalentedAmateur** [comment] 2021-10-03 22:43
Yeah, sorry about the clutter in the log, but I wasn't 100% sure how some of those other fabric elements might or might not be contributing.  It looks like the MCPPPP mod is non-functional in my config (@supsm confirmed what it should be doing), so its presence is a bit of a red herring.

I will give it another shot at getting a much cleaner log for you today.

I also didn't know that various bits were looking inside unloaded resourcepacks (i.e. in the resourcepack folder but not actively loaded in Minecraft), so I'll move some of my inactive packs and mods well away from my Minecraft install to keep them out of the log.

**Comment by UntalentedAmateur** [comment] 2021-10-04 06:59
So, good news and bad news.  The bad news is also the good news.  I can't replicate the issue today.

I unloaded every mod and shader pack and resource pack from the Minecraft install, except for fabricskyboxes, and Minecraft wouldn't even start.   I put back iris-and-sodium, lithium, and starlight, and fabric-api-0.40.1+1.17, which I'd installed last night as part of another mod, and then it was able to start.

**The presence of fabric API seemed to make all the difference**.  I checked with MCPPPP CLI converted packs.  I checked with Awesome Skies and MiASkyboxFabric.  It all seemed to work.  I checked with unconverted packs and made sure they weren't crashing the system.  I checked with and without shaders, and it all worked.  I checked with and without the MCPPPP mod, and it made no difference (so I removed it, as I'd already done the CLI adjustment).  I even checked with completely varied resourcepack load order and only got the expected visual render changes from render order.

The log is rather large and full of stuff, so I won't repaste it, as there's no crashing by fabricskyboxes any more.

**Comment by supsm** [comment] 2021-10-04 18:00
So to confirm, it crashes with only fabricakyboxes and fabric api?

**Comment by UntalentedAmateur** [comment] 2021-10-04 20:34
No.  Having the API in the mod folder seemed to make all the difference.  I was unable to pull everything out of the mod folder and check, without Minecraft crashing to desktop.  I could remove all the resourcepacks and shaders without issue.

When fabric API and fabricskyboxes were present, fabricskyboxes seemed to work and I was able to load and have things like Awesome Skies render correctly.  And I was able to use the MCPPPP CLI to convert OF skyboxes and have them show up.  There were some z-fighting issues, but after playing around with resourcepack order I think I've found that some of the non-skybox packs have skyboxes / sky data hidden in them (I ran MCPPPP CLI over the whole resourcepack folder) and OF tended to blend / hide it.

**Comment by AMereBagatelle** [comment] 2021-10-04 20:48
To be clear, FabricSkyboxes is no longer causing a crash when installed with Fabric API and this issue can be closed?

**Comment by UntalentedAmateur** [comment] 2021-10-04 20:53
I believe this to be the case.

**Comment by AMereBagatelle** [comment] 2021-10-04 20:56
Sounds good, closing.

**Closed as completed by AMereBagatelle** 2021-10-04 20:56 UTC
Labels: bug
