### ISSUE TITLE
startFadeOut parameter not working

### ISSUE THREAD

**Issue by Marcelo20XX** [AMereBagatelle/fabricskyboxes#30] opened 2022-02-09 05:41 UTC
The fade out parameter isn't working, I tested Fade in and is working as intended but Fade out no dice and that parameter is crucial for day night transitions. I am using 1.17.1 Fabric Java Edition...

You can put any value at  "startFadeOut" and "endFadeOut" and the texture will just disappear when it reaches the endFadeOut tick value...

**Comment by AMereBagatelle** [comment] 2022-02-10 00:39
1.17.1 is not fully supported.  Can you test In 1.18 and if the problem persists post your skybox file?

**Comment by Marcelo20XX** [comment] 2022-02-10 01:27
OK I will install a new 1.18 server and report back, I was sticking to 1.17.1 because a lot of mods I use don't have support for 1.18 yet...

**Comment by supsm** [comment] 2022-02-10 18:47
You could use viafabric which would allow you to join older servers

**Comment by AMereBagatelle** [comment] 2022-02-28 02:34
I am not able to reproduce this issue, and have not heard of it happening for others.  I am going to close this issue now, if it still persists on the latest release for you please reopen the issue and post a skybox file that causes the problem.

**Closed as completed by AMereBagatelle** 2022-02-28 02:34 UTC
